# Generated by Django 5.2.8 on 2025-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCollege',
            fields=[
                ('counselling_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('students_count', models.IntegerField()),
            ],
            options={
                'db_table': 'college"."master_college',
            },
        ),
    ]
